import React from "react";

export default function TermsAndConditions() {
  return (
    <div className="min-h-screen bg-[#FDFBF7] text-[#181818] py-16 px-4 font-sans">
      <div className="max-w-3xl mx-auto bg-white rounded-xl shadow-lg p-8">
        <h1 className="text-4xl font-black mb-6 text-center">Terms & Conditions</h1>
        <p className="mb-4 text-sm text-gray-600 text-center">Last updated: August 2, 2025</p>
        <h2 className="text-2xl font-bold mt-8 mb-2">1. Acceptance of Terms</h2>
        <p className="mb-4">By accessing or using the Casego website and services, you agree to be bound by these Terms & Conditions. If you do not agree to these terms, please do not use our services.</p>
        <h2 className="text-2xl font-bold mt-8 mb-2">2. Description of Service</h2>
        <p className="mb-4">Casego is a SaaS platform that enables users to connect their databases or Shopify stores by providing credentials or access tokens. Our AI-powered system delivers analytics, insights, and answers to your queries via WhatsApp messages.</p>
        <h2 className="text-2xl font-bold mt-8 mb-2">3. User Responsibilities</h2>
        <p className="mb-4">You are responsible for providing accurate and up-to-date database credentials or Shopify access tokens. You must have the legal right to access and share this data. You are responsible for all activity conducted through your account and for maintaining the confidentiality of your credentials.</p>
        <h2 className="text-2xl font-bold mt-8 mb-2">4. Data Access and Security</h2>
        <p className="mb-4">By using our service, you grant Casego permission to access your connected databases and/or Shopify store solely for the purpose of generating analytics and responding to your queries. We implement reasonable technical and organizational measures to protect your data, but cannot guarantee absolute security. You acknowledge and accept the risk of transmitting sensitive data online.</p>
        <h2 className="text-2xl font-bold mt-8 mb-2">5. AI-Generated Responses</h2>
        <p className="mb-4">Analytics and answers provided via WhatsApp are generated by AI based on your data and questions. While we strive for accuracy, Casego does not guarantee the completeness, accuracy, or suitability of any information provided. You are solely responsible for any decisions made based on this information.</p>
        <h2 className="text-2xl font-bold mt-8 mb-2">6. User Consent</h2>
        <p className="mb-4">By using Casego, you consent to us accessing your database or Shopify data, processing it, and sending responses to your WhatsApp number. You also consent to our use of third-party service providers to facilitate these services.</p>
        <h2 className="text-2xl font-bold mt-8 mb-2">7. Limitation of Liability</h2>
        <p className="mb-4">Casego and its affiliates are not liable for any direct, indirect, incidental, consequential, or punitive damages arising from your use of the service, including but not limited to data loss, unauthorized access, or inaccurate analytics. The service is provided on an &quot;as is&quot; and &quot;as available&quot; basis.</p>
        <h2 className="text-2xl font-bold mt-8 mb-2">8. Compliance and Restrictions</h2>
        <p className="mb-4">You agree not to use Casego for any unlawful activities or in violation of data privacy laws. You are responsible for ensuring your use of Casego complies with all applicable regulations.</p>
        <h2 className="text-2xl font-bold mt-8 mb-2">9. Changes to Terms</h2>
        <p className="mb-4">We reserve the right to update or modify these Terms & Conditions at any time. Changes will be posted on this page with an updated effective date. Continued use of the service constitutes acceptance of the new terms.</p>
        <h2 className="text-2xl font-bold mt-8 mb-2">10. Contact Us</h2>
        <p className="mb-4">If you have any questions about these Terms & Conditions, please contact us at <a href="mailto:info@casego.com" className="underline text-blue-600">info@casego.com</a>.</p>
      </div>
    </div>
  );
}
